### PR TITLE
Change class name from Settings to Setting

### PR DESCRIPTION
**Pull request by dkniffin**
To follow rails conventions, the model should be singular.

### CODE REVIEW

**Comment by artofhuman** [comment]
Hi, Derek. Thanks for you PR. But i think this change breaks compatibility with older versions. And in documentation `rails-settings-cached` exists example. 

``` ruby
class Settings < RailsSettings::CachedSettings
end
```

**Comment by dkniffin** [comment]
Alright, makes sense. Would you be willing to add a way to change the class through a setting or something? Maybe there's even a way to do that already?

**Comment by artofhuman** [comment]
Yes, we need configuration. I make this today

**Comment by artofhuman** [comment]
@dkniffin see please https://github.com/artofhuman/activeadmin_settings_cached/commit/d1b4dbb3ac1e1f1f8af2b5aa3aa5fe85de135bc8

**Comment by dkniffin** [comment]
Looks good. Thanks! I fixed some grammar and whatnot in the readme via #8

**Pull request closed without merging**
